addSbtPlugin("org.scalameta"     % "sbt-scalafmt" % "2.3.2")
addSbtPlugin("com.github.gseitz" % "sbt-release"  % "1.0.13")
addSbtPlugin("com.typesafe.sbt"  % "sbt-git"      % "1.0.0")
addSbtPlugin("org.xerial.sbt"    % "sbt-sonatype" % "3.10.0")
addSbtPlugin("com.jsuereth"      % "sbt-pgp"      % "2.0.1")
